#...............................................................................
#
#  This file is part of the AXL library.
#
#  AXL is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/axl/license.txt
#
#...............................................................................

branches:
    only:
        - master

image: Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\axl
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc10
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc14

install:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%
    - call ci\appveyor\install.bat

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_FLAGS%
    - cmake --build . -- %MSBUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION%
