#...............................................................................
#
#  This file is part of the AXL library.
#
#  AXL is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/axl/license.txt
#
#...............................................................................

dist:     trusty
sudo:     required
language: cpp

compiler:
    - gcc
    - clang

before_install:
    - mkdir -p dep
    - cd dep

    - echo Installing cmake...

    - CMAKE_VERSION=3.3.2
    - CMAKE_VERSION_DIR=v3.3
    - CMAKE_OS=x86_64

    - CMAKE_FILE=cmake-$CMAKE_VERSION-Linux-$CMAKE_OS.tar.gz
    - CMAKE_URL=http://www.cmake.org/files/$CMAKE_VERSION_DIR/$CMAKE_FILE

    - wget --quiet $CMAKE_URL

    - mkdir -p cmake
    - tar --strip-components=1 -xzf $CMAKE_FILE -C cmake
    - export PATH=$ROOT_DIR/dep/cmake/bin:$PATH

    - sudo apt-get -qq update

    - echo Installing libpcap...
    - sudo apt-get install -y libpcap-dev

    - echo Installing libusb...
    - sudo apt-get install -y libusb-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
