#...............................................................................
#
#  This file is part of the AXL library.
#
#  AXL is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/axl/license.txt
#
#...............................................................................

dist: trusty
sudo: required

language: cpp

compiler:
    - gcc
    - clang

script:
    - uname -a
    - cat /etc/*-release

    - cmake --version
    - gcc --version
    - clang --version

    - mkdir build
    - cd build
    - cmake ..
    - make
